services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: next_core_app_prod
    env_file:
      - ./docker/env/.env.production
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: next_core_nginx_prod
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
