services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: next_core_app_dev
    env_file:
      - ./docker/env/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev -- -H 0.0.0.0 -p 3000

  nginx:
    image: nginx:1.27-alpine
    container_name: next_core_nginx_dev
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
