// <auto-generated />
using System;
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationDB.Migrations.System
{
    [DbContext(typeof(SystemDbContext))]
    partial class SystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.Models.ts_LocalizedMessages", b =>
                {
                    b.Property<string>("MessageCode")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("MessageType")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageNameEN")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("MessageNameTH")
                        .HasColumnType("VARCHAR(500)");

                    b.Property<string>("Remark")
                        .HasColumnType("VARCHAR(256)");

                    b.HasKey("MessageCode", "MessageType");

                    b.ToTable("ts_LocalizedMessages", (string)null);
                });

            modelBuilder.Entity("Application.Models.ts_LocalizedResources", b =>
                {
                    b.Property<string>("ScreenCode")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("ObjectID")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("ResourcesEN")
                        .HasColumnType("VARCHAR(256)");

                    b.Property<string>("ResourcesTH")
                        .HasColumnType("VARCHAR(256)");

                    b.HasKey("ScreenCode", "ObjectID");

                    b.ToTable("ts_LocalizedResources", (string)null);
                });

            modelBuilder.Entity("ApplicationDB.Models.System.ts_ImportLog", b =>
                {
                    b.Property<string>("JobLogId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FileFolder")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FinishDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FtpServername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InterfaceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InterfaceFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InterfaceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProcessBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRecord")
                        .HasColumnType("int");

                    b.HasKey("JobLogId");

                    b.ToTable("ts_ImportLog", (string)null);
                });

            modelBuilder.Entity("ApplicationDB.Models.System.ts_ImportLogDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorDetail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobLogId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("RowNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ts_ImportLogDetail", (string)null);
                });

            modelBuilder.Entity("ApplicationDB.Models.System.ts_Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModuleNameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModuleNameTH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ts_Module", (string)null);
                });

            modelBuilder.Entity("ApplicationDB.Models.System.ts_Screen", b =>
                {
                    b.Property<string>("ScreenId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FunctionCode")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("MainMenuFlag")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameEN")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NameTH")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PageTitleNameEN")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PageTitleNameTH")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("PermissionFlag")
                        .HasColumnType("bit");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<string>("SubModuleCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SupportDeviceType")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ScreenId");

                    b.ToTable("ts_Screen", (string)null);
                });

            modelBuilder.Entity("ApplicationDB.Models.System.ts_ScreenFunction", b =>
                {
                    b.Property<int>("FunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FunctionId"));

                    b.Property<int>("FunctionCode")
                        .HasColumnType("int");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("FunctionId");

                    b.ToTable("ts_ScreenFunction", (string)null);
                });

            modelBuilder.Entity("ApplicationDB.Models.System.ts_SubModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconClass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<string>("SubModuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubModuleNameEN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubModuleNameTH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ts_SubModule", (string)null);
                });

            modelBuilder.Entity("ApplicationDB.Models.System.ts_SystemConfig", b =>
                {
                    b.Property<string>("ConfigCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ConfigCode");

                    b.Property<string>("ConfigDesc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ConfigDesc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValueDate");

                    b.Property<decimal?>("ValueDecimal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValueDecimal");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("int")
                        .HasColumnName("ValueInt");

                    b.Property<string>("ValueVarchar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValueVarchar");

                    b.Property<string>("ValueVarchar2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValueVarchar2");

                    b.Property<string>("ValueVarchar3")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValueVarchar3");

                    b.HasKey("ConfigCode");

                    b.ToTable("ts_SystemConfig", (string)null);
                });

            modelBuilder.Entity("ApplicationDB.Models.System.ts_URLConfig", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Remark")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Remark");

                    b.Property<string>("URL")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("URL");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDateTime");

                    b.Property<string>("UpdateUserID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UpdateUserID");

                    b.HasKey("Code");

                    b.ToTable("ts_URLConfig", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
